# Configure app VM get nginx up and running, and set up our demo app.
---

- hosts: web
  gather_facts: yes
  become: true
  tasks:
  - name: copy app folder to web machine
    synchronize:
      src: /home/vagrant/code/app
      dest: /home/vagrant

  - name: copy reverse proxy config
    synchronize:
      src: /home/vagrant/code/default
      dest: /etc/nginx/sites-available/

  - name: set env var DB_HOST
    lineinfile:
      path: /home/vagrant/.bashrc
      line: export DB_HOST='mongodb://192.168.56.11:27017/posts'
      create: yes

#  - name: download a specific version of nodejs
#    shell: curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -

  - name: install the required packages (with downloaded nodejs downgrade)
    apt:
      pkg:
        - nginx
#        - nodejs
        - npm
      update_cache: yes

  - name: nginx restart
    service: name=nginx state=restarted

  - name: nginx enable
    service: name=nginx enabled=yes

  - name: install and run the app
    become_user: vagrant
    environment:
      DB_HOST: mongodb://192.168.56.11:27017/posts
    shell:
       cd app; node seeds/seed.js; npm install; screen -d -m npm start