# Configure app VM get nginx up and running, and set up our demo app.
---
- hosts: web
  remote_user: root
  gather_facts: yes
  become: true #Gain Sudo(?)

  tasks:
  - name: Installing Nginx web-server in our app machine
    apt: pkg=nginx state=present
  - name: Write the app folder out to the app vm
    ansible.builtin.copy:
      src: /home/vagrant/app
      dest: /home/vagrant

